which_project: &which_project worldFarm

RUN: &run
  projectName: *which_project
  SWEEP_SPACING: 30
  ACTIVITY_NUM: 5
  BLACKLIST_PACKAGE:
    - com.netease.cloudmusic
    - com.meizu.media.music
    - com.android.mediacenter
    - com.tencent.qqmusic

worldFarm:
  <<: *run
  account:
    username: 632948101@qq.com
    password: 123456
  ACTIVITY_NAME:
  PACKAGE_NAME:
    - hc.ng.mt
  DEFAULT_PACKAGE_NAME:
  MOBLIE:
    - 15388126080
    - 15388126081
    - 15388126082
    - 15388126083
    - 15388126084
    - 15388126085
    - 15388126086
    - 15388126087
    - 15388126088
